/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

/**
 *
 * @author usuario
 */
public class Admin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    private boolean isAdmin = false;
    private int userId = -1;
    public Admin(boolean isAdmin, int userId) {
        initComponents();
        this.isAdmin = isAdmin;
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnDrivers = new javax.swing.JButton();
        BtnTrucks = new javax.swing.JButton();
        BtnAssign = new javax.swing.JButton();
        BtnMaintenance = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();
        BtnPendient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACIÓN");

        BtnDrivers.setText("Administrar conductores");
        BtnDrivers.addActionListener(this::BtnDriversActionPerformed);

        BtnTrucks.setText("Administrar camiones");
        BtnTrucks.addActionListener(this::BtnTrucksActionPerformed);

        BtnAssign.setText("Asignar conductores a camiones");
        BtnAssign.addActionListener(this::BtnAssignActionPerformed);

        BtnMaintenance.setText("Ver mantenciones");
        BtnMaintenance.addActionListener(this::BtnMaintenanceActionPerformed);

        BtnLogout.setText("Cerrar sesión");
        BtnLogout.addActionListener(this::BtnLogoutActionPerformed);

        BtnPendient.setText("Ver pendientes");
        BtnPendient.addActionListener(this::BtnPendientActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(BtnDrivers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnTrucks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPendient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDrivers)
                .addGap(18, 18, 18)
                .addComponent(BtnTrucks)
                .addGap(18, 18, 18)
                .addComponent(BtnAssign)
                .addGap(18, 18, 18)
                .addComponent(BtnMaintenance)
                .addGap(18, 18, 18)
                .addComponent(BtnPendient)
                .addGap(18, 18, 18)
                .addComponent(BtnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDriversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDriversActionPerformed

        //Abre la ventana de los conductores
        Drivers drivers = new Drivers(isAdmin, userId);
        drivers.setVisible(true);
        drivers.setLocationRelativeTo(null);
        drivers.pack();
        this.dispose();
    }//GEN-LAST:event_BtnDriversActionPerformed

    private void BtnTrucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrucksActionPerformed

        //Abre la ventana de los camiones
        Trucks trucks = new Trucks(isAdmin, userId);
        trucks.setVisible(true);
        trucks.setLocationRelativeTo(null);
        trucks.pack();
        this.dispose();
    }//GEN-LAST:event_BtnTrucksActionPerformed

    private void BtnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAssignActionPerformed

        //Abre la ventana para asignar camiones a conductores
        Assignments assign = new Assignments(isAdmin, userId);
        assign.setVisible(true);
        assign.setLocationRelativeTo(null);
        assign.pack();
        this.dispose();
    }//GEN-LAST:event_BtnAssignActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed

        //Cierra sesión
        Login login = new Login(isAdmin, userId);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaintenanceActionPerformed

        //Abre la ventana de las mantenciones
        Maintenance maintenance = new Maintenance(isAdmin, userId);
        maintenance.setVisible(true);
        maintenance.setLocationRelativeTo(null);
        maintenance.pack();
        this.dispose();
    }//GEN-LAST:event_BtnMaintenanceActionPerformed

    private void BtnPendientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPendientActionPerformed

        //Se ve los pendientes que no se lograron guardar
    }//GEN-LAST:event_BtnPendientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAssign;
    private javax.swing.JButton BtnDrivers;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnMaintenance;
    private javax.swing.JButton BtnPendient;
    private javax.swing.JButton BtnTrucks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
