/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import Conexion.BasedeDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Assignments extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Assignments.class.getName());

    private int idCamion = -1;
    private int idConductor = -1;

    /**
     * Creates new form Assignments
     */
    private boolean isAdmin = false;
    public Assignments(boolean isAdmin) {
        initComponents();
        this.isAdmin = isAdmin;
        TblDrivers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDriversMouseClicked(evt);
            }
        });
        TblTrucks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbTrucksMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTrucks = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDrivers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TxtTruck = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtDriver = new javax.swing.JTextField();
        BtnAssings = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnByID = new javax.swing.JButton();
        TxtTruckId = new javax.swing.JTextField();
        TxtDriverId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMIONES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONDUCTORES");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TblTrucks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblTrucks);

        TblDrivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TblDrivers);

        jLabel3.setText("Camión seleccionado:");

        jLabel4.setText("Conductor seleccionado:");

        BtnAssings.setText("Asignar por tabla");
        BtnAssings.addActionListener(this::BtnAssingsActionPerformed);

        BtnBack.setText("Volver");
        BtnBack.addActionListener(this::BtnBackActionPerformed);

        jButton1.setText("Vaciar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        BtnByID.setText("Asignar por ID");
        BtnByID.addActionListener(this::BtnByIDActionPerformed);

        TxtTruckId.setText("ID del camión");
        TxtTruckId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtTruckIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtTruckIdFocusLost(evt);
            }
        });

        TxtDriverId.setText("ID del conductor");
        TxtDriverId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtDriverIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtDriverIdFocusLost(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE LOS IDS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDriver))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTruck))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnAssings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtTruckId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnByID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnBack))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TxtTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtTruckId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBack)
                    .addComponent(BtnAssings)
                    .addComponent(BtnByID)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cargarCamiones();
        cargarConductores();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TxtDriver.setText("");
        TxtTruck.setText("");
        idCamion = -1;
        idConductor = -1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnAssingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAssingsActionPerformed
        // TODO add your handling code here:
        // Validar selección
        if (idCamion == -1 || idConductor == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un camión y un conductor",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        BasedeDatos bd = new BasedeDatos();
        Connection conn = bd.conectar();

        if (conn != null) {
            try {
                // Verificar si ya existe la asignación
                String checkSql = "SELECT * FROM camion_conductor WHERE id_camion = ? OR id_conductor = ?";
                PreparedStatement checkPs = conn.prepareStatement(checkSql);
                checkPs.setInt(1, idCamion);
                checkPs.setInt(2, idConductor);
                ResultSet rs = checkPs.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                            "El camión o el conductor ya están asignados",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

                // Insertar asignación
                String sql = "INSERT INTO camion_conductor (id_camion, id_conductor) VALUES (?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idCamion);
                ps.setInt(2, idConductor);

                int resultado = ps.executeUpdate();

                if (resultado > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Asignación realizada correctamente",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE
                    );

                    // Limpiar campos
                    TxtTruck.setText("");
                    TxtDriver.setText("");
                    idCamion = -1;
                    idConductor = -1;

                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo asignar",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_BtnAssingsActionPerformed

    private void BtnByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnByIDActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener los Ids
            int camionID = Integer.parseInt(TxtTruckId.getText().trim());
            int conductorID = Integer.parseInt(TxtDriverId.getText().trim());

            BasedeDatos bd = new BasedeDatos();
            Connection conn = bd.conectar();

            if (conn != null) {

                // Verificar si ya existe
                String checkSql = "SELECT * FROM camion_conductor WHERE id_camion = ? OR id_conductor = ?";
                PreparedStatement checkPs = conn.prepareStatement(checkSql);
                checkPs.setInt(1, camionID);
                checkPs.setInt(2, conductorID);
                ResultSet rs = checkPs.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                            "El camión o el conductor ya están asignados",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

                // Insertar
                String sql = "INSERT INTO camion_conductor (id_camion, id_conductor) VALUES (?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, camionID);
                ps.setInt(2, conductorID);

                int resultado = ps.executeUpdate();

                if (resultado > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Asignación realizada correctamente",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE
                    );

                    // Limpiar campos
                    TxtTruckId.setText("");
                    TxtDriverId.setText("");

                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo asignar",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese IDs válidos (números)",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnByIDActionPerformed

    private void TxtTruckIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtTruckIdFocusGained
        // TODO add your handling code here:
        if ("ID del camión".equals(this.TxtTruckId.getText())) {
            TxtTruckId.setText("");
        }
    }//GEN-LAST:event_TxtTruckIdFocusGained

    private void TxtTruckIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtTruckIdFocusLost
        // TODO add your handling code here:
        if ("".equals(this.TxtTruckId.getText())) {
            TxtTruckId.setText("ID del camión");
        }
    }//GEN-LAST:event_TxtTruckIdFocusLost

    private void TxtDriverIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDriverIdFocusGained
        // TODO add your handling code here:
        if ("ID del conductor".equals(this.TxtDriverId.getText())) {
            TxtDriverId.setText("");
        }
    }//GEN-LAST:event_TxtDriverIdFocusGained

    private void TxtDriverIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDriverIdFocusLost
        // TODO add your handling code here:
        if ("".equals(this.TxtDriverId.getText())) {
            TxtDriverId.setText("ID del conductor");
        }
    }//GEN-LAST:event_TxtDriverIdFocusLost

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin(isAdmin);
        admin.setVisible(true);
        admin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void cargarConductores() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");

        BasedeDatos bd = new BasedeDatos();
        Connection conn = bd.conectar();

        if (conn != null) {
            try {
                String sql = "SELECT ID_conductor, nombre FROM conductores";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[2];
                    fila[0] = rs.getInt("ID_conductor");
                    fila[1] = rs.getString("nombre");

                    modelo.addRow(fila);
                }

                TblDrivers.setModel(modelo);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }

    private void cargarCamiones() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Patente");
        modelo.addColumn("Modelo");

        BasedeDatos bd = new BasedeDatos();
        Connection conn = bd.conectar();

        if (conn != null) {
            try {
                String sql = "SELECT id_camion, patente, modelo FROM camiones";
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = new Object[3];
                    fila[0] = rs.getInt("id_camion");
                    fila[1] = rs.getString("patente");
                    fila[2] = rs.getString("modelo");

                    modelo.addRow(fila);
                }

                TblTrucks.setModel(modelo);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }

    private void TableDriversMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = TblDrivers.getSelectedRow();

        if (fila >= 0) {
            idConductor = Integer.parseInt(TblDrivers.getValueAt(fila, 0).toString());
            String nombre = TblDrivers.getValueAt(fila, 1).toString();

            TxtDriver.setText(nombre);
        }
    }

    private void TbTrucksMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = TblTrucks.getSelectedRow();

        if (fila >= 0) {
            idCamion = Integer.parseInt(TblTrucks.getValueAt(fila, 0).toString());
            String patente = TblTrucks.getValueAt(fila, 1).toString();
            String modelo = TblTrucks.getValueAt(fila, 2).toString();

            TxtTruck.setText(patente + " - " + modelo);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Assignments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAssings;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnByID;
    private javax.swing.JTable TblDrivers;
    private javax.swing.JTable TblTrucks;
    private javax.swing.JTextField TxtDriver;
    private javax.swing.JTextField TxtDriverId;
    private javax.swing.JTextField TxtTruck;
    private javax.swing.JTextField TxtTruckId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
